-- create_tables.sql
-- Create 8 tables for Employee & Project Management System

-- 1. DEPARTMENT TABLE
CREATE TABLE DEPARTMENT (
    DEPT_ID NUMBER(3) PRIMARY KEY,
    DEPT_NAME VARCHAR2(50),
    LOCATION VARCHAR2(50)
);

-- 2. EMPLOYEE TABLE
CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER(5) PRIMARY KEY,
    EMP_NAME VARCHAR2(50),
    GENDER CHAR(1),
    DOB DATE,
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(15),
    HIRE_DATE DATE,
    DEPT_ID NUMBER(3),
    JOB_ROLE VARCHAR2(50),
    MANAGER_ID NUMBER(5),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(EMP_ID)
);

-- 3. CLIENT TABLE
CREATE TABLE CLIENT (
    CLIENT_ID NUMBER(5) PRIMARY KEY,
    CLIENT_NAME VARCHAR2(100),
    CONTACT_PERSON VARCHAR2(50),
    CONTACT_EMAIL VARCHAR2(100),
    COUNTRY VARCHAR2(50)
);

-- 4. PROJECT TABLE
CREATE TABLE PROJECT (
    PROJECT_ID NUMBER(5) PRIMARY KEY,
    PROJECT_NAME VARCHAR2(100),
    CLIENT_ID NUMBER(5),
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR2(20),
    TEAM_LEAD_ID NUMBER(5),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID),
    FOREIGN KEY (TEAM_LEAD_ID) REFERENCES EMPLOYEE(EMP_ID)
);

-- 5. TECH_STACK TABLE
CREATE TABLE TECH_STACK (
    TECH_ID NUMBER(3) PRIMARY KEY,
    TECH_NAME VARCHAR2(50),
    CATEGORY VARCHAR2(30)
);

-- 6. PROJECT_TECH TABLE (Mapping Table)
CREATE TABLE PROJECT_TECH (
    PROJECT_ID NUMBER(5),
    TECH_ID NUMBER(3),
    PRIMARY KEY (PROJECT_ID, TECH_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (TECH_ID) REFERENCES TECH_STACK(TECH_ID)
);

-- 7. SALARY TABLE
CREATE TABLE SALARY (
    SALARY_ID NUMBER(5) PRIMARY KEY,
    EMP_ID NUMBER(5),
    BASIC_PAY NUMBER(10,2),
    BONUS NUMBER(10,2),
    DEDUCTIONS NUMBER(10,2),
    NET_PAY NUMBER(10,2),
    PAY_DATE DATE,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

-- 8. PERFORMANCE TABLE
CREATE TABLE PERFORMANCE (
    REVIEW_ID NUMBER(5) PRIMARY KEY,
    EMP_ID NUMBER(5),
    REVIEW_DATE DATE,
    RATING NUMBER(2,1),
    FEEDBACK VARCHAR2(255),
    NEXT_PROMOTION_DATE DATE,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);