-- queries.sql
-- Key queries for Employee-Project Management System

-- 1. Employee details with department
SELECT E.EMP_NAME, E.JOB_ROLE, D.DEPT_NAME, D.LOCATION
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID;

-- 2. Project with client and team lead info
SELECT P.PROJECT_NAME, C.CLIENT_NAME, E.EMP_NAME AS TEAM_LEAD
FROM PROJECT P
JOIN CLIENT C ON P.CLIENT_ID = C.CLIENT_ID
JOIN EMPLOYEE E ON P.TEAM_LEAD_ID = E.EMP_ID;

-- 3. Employee technologies per project
SELECT E.EMP_NAME, P.PROJECT_NAME, T.TECH_NAME
FROM EMPLOYEE E
JOIN PROJECT P ON P.TEAM_LEAD_ID = E.EMP_ID
JOIN PROJECT_TECH PT ON P.PROJECT_ID = PT.PROJECT_ID
JOIN TECH_STACK T ON PT.TECH_ID = T.TECH_ID;

-- 4. Employee salary info
SELECT E.EMP_NAME, S.BASIC_PAY, S.BONUS, S.NET_PAY, S.PAY_DATE
FROM EMPLOYEE E
JOIN SALARY S ON E.EMP_ID = S.EMP_ID;

-- 5. Performance review details
SELECT E.EMP_NAME, P.REVIEW_DATE, P.RATING, P.FEEDBACK, P.NEXT_PROMOTION_DATE
FROM EMPLOYEE E
JOIN PERFORMANCE P ON E.EMP_ID = P.EMP_ID;

-- 6. Employees earning more than 5000
SELECT EMP_NAME, NET_PAY
FROM EMPLOYEE E
JOIN SALARY S ON E.EMP_ID = S.EMP_ID
WHERE S.NET_PAY > 5000;

-- 7. Second highest salary
SELECT MAX(NET_PAY) AS SECOND_HIGHEST_PAY
FROM SALARY
WHERE NET_PAY < (SELECT MAX(NET_PAY) FROM SALARY);